Repository wyg1997/feishu-new_bing_bot, pull requests merged in 2023-04, with the labels that each got.

#3 Refine aliyun config and enable regex module
  code/core/tools.py
  code/handlers/dispatchers.py
  code/requirements.txt
  s.yaml
Labels: build

#5 Feat: support bot pool and new_bing chat
  .gitignore
  code/core/bot.py
  code/core/data_structure.py
  code/core/service.py
  code/handlers/dispatchers.py
  code/handlers/helper_handle.py
  code/handlers/new_bing_handle.py
  code/index.py
Labels: feature

#6 Support card builder
  code/core/bot.py
  code/core/card_builder.py
  code/core/service.py
  code/handlers/dispatchers.py
  code/handlers/helper_handle.py
Labels: enhancement, feature

#9 Adapt the start command for railway
  Procfile
  code/core/config.py
  code/index.py
  code/requirements.txt
Labels: build

#11 Refactor handler register and add bot register
  .gitignore
  code/core/__init__.py
  code/core/bot.py
  code/core/data_structure.py
  code/core/register.py
  code/handlers/__init__.py
  code/handlers/all/__init__.py
  code/handlers/all/helper_handle.py
  code/handlers/all/new_bing_handle.py
  code/handlers/all/repeat_handle.py
  code/handlers/dispatchers.py
  code/handlers/new_bing_handle.py
  code/handlers/register.py
Labels: enhancement, feature, refactor
